site_name: CDO scripts
repo_url: https://github.com/andr-groth/cdo-scripts
nav:
  - 'index.md'
  - 'Main scripts':
    - 'get_anom.md'
    - 'get_eofs.md'
    - 'get_pcs.md'
  - 'Combined scripts':
    - 'prepare_data.md'
    - 'prepare_data2.md'

  - 'Additional scripts':
    - 'merge.md'
theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
markdown_extensions:
  - admonition
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/andr-groth