site_name: CDO scripts
nav:
  - 'index.md'
  - 'Main scripts':
    - 'get_anom.md'
    - 'get_eofs.md'
    - 'get_pcs.md'
  - 'Combined scripts':
    - 'prepare_data.md'
    - 'prepare_data2.md'

  - 'Additional scripts':
    - 'merge.md'
theme:
  name: readthedocs
markdown_extensions:
  - admonition